version: '3.8'

services:
  db:
    image: percona/percona-server:8.0
    container_name: percona-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf:ro  # Percona prefers /etc/my.cnf over /etc/mysql/conf.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fastapi-server
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - "8000:8000"

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    command:
      - "--mysqld.username=taskuser:taskpass"
      - "--mysqld.address=db:3306"
    depends_on:
      - db
    ports:
      - "9104:9104"

volumes:
  mysql-data:
